service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

environment:
  DB_HOST:
  DB_PORT:
  DB_DATABASE:
  DB_USERNAME: postgres
  DB_PASSWORD:

functions:
  getProductList:
    handler: src/handler.getProductList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: src/handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true
