service: product-service

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    DB_HOST:
    DB_PORT:
    DB_DATABASE:
    DB_USERNAME:
    DB_PASSWORD:

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  getProductList:
    handler: src/handler.getProductList
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: src/handler.getProductById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                productId: true

  createNewProduct:
    handler: src/handler.createProduct
    events:
      - http:
          path: products
          method: post
          cors: true
